spring:
    profiles: development
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/medstore
        username: postgres
        password: fuckers
    jpa:
        database_platform: org.hibernate.dialect.PostgreSQLDialect
---
spring:
    profiles: production
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://ec2-54-163-239-102.compute-1.amazonaws.com:5432/d596bqj5uf082d
        username: tjlqraxbdopulz
        password: d5TzXctQbNCdHue02LNMnaSQ98
    jpa:
        database_platform: org.hibernate.dialect.PostgreSQLDialect